jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm lint:md

name: Lint Markdown

on:
  push:
    branches:
      - main
  pull_request:
